name: SuperOptimization
author: DragoVN - Goldenra -Slater
version: 0.1
main: DragoVN\main
api: [3.0.0]

commands:
  spo:
    usage: /spo [---]
    description: "Open menu ui for superoptimization."    
    permission: super.optimization
    default: op
